version: "3"
services:
  client:
    build: ./services/client
    volumes:
      - ../service/client:/usr/src/twittersearch/client
    ports:
      - "3000:3000"
  server:
    build: ./services/server
    volumes:
      - ../service/server:/usr/src/twittersearch/server
    ports:
      - "8000:8000"
    tty: true
